parameters:
#    unlock_phone_form.example.class: Unlock\Phone\FormBundle\Example

services:
#    unlock_phone_form.example:
#        class: %unlock_phone_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
